### PR TITLE
Fix class hashes

### PR DESCRIPTION
**Pull request by MatthiasSaihttam**
Fixes some of the issues caused by #175.
Current status: 

- [X] Editor settings button (dark theme!)
- [X] Program buttons (vote button and blue colors and css)
- [X] Program info (last updated, hidden, that stuff)
- [x] Merge with master
- [x] Fix lint errors
- [x] All discussion code (but that was still mostly broken from the discussion update before this)
- [x] Selecting T&T tab by default
- [ ] Main CSS rules that are broken: blue sort buttons on browse projects page, Error Buddy overlaps with the Editor Setting button, outlines on discussion content, and some others.
- [ ] Toggle Editor Button (not a priority)
- [ ] Program Author hovercards (still broken from `KAdefine` being removed; no idea how to fix)
- [ ] Report button on comments
- [ ] Bug: I don't think the program report button is working if you're logged in, or something weird like that
- [ ] Bug: comment flag text is weird if you're not logged in

Places where comments aren't found (bugs, but not a huge deal)
- [ ] If you post (brand new comments)
- [ ] If the sort is changed (recent/top)
- [ ] If you open a direct link to a comment (replies are automatically unfolded and aren't found)
- [ ] If loading takes more than 2 seconds (has happened to me). We should probably bump the time to like 5 seconds. It would be cool if `querySelectorPromise` searched more often at first and then slowed down.

### CODE REVIEW

**Comment by lukekrikorian** [comment]
I'd honestly be fine removing some of the lesser useful features like the Hide Editor button, they're only going to be more work in the future.

**Comment by MatthiasSaihttam** [comment]
This PR is now at the point where it *could* be merged. There are still a fair number of bugs and a couple of unimplemented features. (I updated the todo list in the original comment.) But all areas of the extension are now mostly working.

**Comment by JettBurns14** [comment]
Agreed with Luke, I’ve never really used the hide editor button.

**Comment by lukekrikorian** [comment]
I would suggest merging ASAP, even if there are a few parts that we could clean up later. It's more important that we have the majority of features fixed in the live version.

**Comment by MatthiasSaihttam** [comment]
That's what I'm thinking. And I don't think I'll have time to work on it more until this weekend, so I just added a 4.6.3 commit and I'll merge once Travis finishes. So you should be go to `npm run release` and publish, @lukekrikorian.

**Comment by lukekrikorian** [comment]
Published on Chrome/Firefox!

**Pull request merged**
