### PR TITLE
Center program titles and discussion

### PR DESCRIPTION
**Pull request by MatthiasSaihttam**
I'm not OCD, but it bothers me when things aren't centered.
 - KA never centered program titles, but just kind of left aligned them a third of the way across the page.
 - T&T under programs were being pushed far to the left by KA and the extension's CSS. This centers the discussion container under programs and squeezes the Community Guidelines into a slightly smaller area to the right.

Before:
screen shot 2018-11-03 at 1 07 48 pm
After:
screen shot 2018-11-03 at 1 08 31 pm

### CODE REVIEW

**Comment by JettBurns14** [comment]
KA moved program titles to the left side to match the rest of the headers on the site, which are all left aligned. I think centering the T&T is cool but Idk about the titles. Can you screenshot the centered titles?

**Comment by lukekrikorian** [comment]
image

This is what the change looks like. LGTM

**Comment by MatthiasSaihttam** [comment]
It definitely makes sense to left align titles on pages like this, where the content is all left aligned. screen shot 2018-11-14 at 8 13 44 am

But on programs and projects, the only thing that fell along that line was the left side of discussion, which you can't see at the same time as the title most of the time (you have to scroll). And now even discussion is centered. Here's a picture without the extension: 
screen shot 2018-11-14 at 8 10 51 am

**Comment by JettBurns14** [comment]
Ok, if you can get just the program titles centered I think it’s fine.

**Comment by lukekrikorian** [comment]
The CSS class applies to page titles on articles as well, it's not specific enough. 
image

**Pull request merged**
