### PR TITLE
HLJS synax restriction

### PR DESCRIPTION
**Pull request by EthanLuisMcDonough**

### CODE REVIEW

**Comment by EthanLuisMcDonough** [comment]
I'm mostly attached to HighlightJS because of its auto detection feature.  It isn't the best system in the world, but trying to write a better one would another feature to maintain and might require a lot more parsing than one might initially think.  The system in your PR seems to be a bit janky.  For example, it recognizes the following as JS:
```js
@import "thingy.css";

.thingy {
    rule: blah;
}
```
and this as CSS:
```css
var options = { a: 20 };
var quirk = "aaaaa";
```
If you can find an external library that's better at detecting languages than HLJS, we can use that alongside prism.  But as is, I don't think the styling is a good reason to switch to Prism.  The style can easily be changed to one of their [many existing themes](https://github.com/highlightjs/highlight.js/tree/main/src/styles).  If we really wanted to, we could make a custom one specifically tailored to look like Prism's styling.

**Comment by MatthiasPortzel** [comment]
Here are those examples in HLJS with the Atom-one-light theme. I'd support switching to that.
image
OJSE: https://ourjseditor.com/program/_G5TdQ

**Comment by EthanLuisMcDonough** [comment]
Okay, I added that theme to the PR.  I also made it so that the dark version of the theme is applied when the user uses a dark theme in the editor.

**Comment by MatthiasPortzel** [comment]
Sorry for releasing the other version of the code. I didn't know if there was a reason you didn't merge this. I respect that you're kind of trying to be professional by creating a branch and PR. But I don't really think that makes sense for this project at this point. If you had merged this I would have pushed it instead.

**Pull request merged**
