### PR TITLE
Fix buttons and flag reasons on project pages

### PR DESCRIPTION
**Pull request by An0n3m0us**
Since KA changed the HTML code for the buttons on project pages, the custom buttons created in the extension have not been showing up.
This PR intends to update the extension code to suit the changes on the KA site.

- [x] Update old container query to find new container set by KA developers
- [x] Fix styling
- [x] Check custom button functionalities working correctly
- [x] Fix flag reasons
- [ ] Fix vote button
- [ ] Flag count + reasons do not update when a flag is added by the current user

image

### CODE REVIEW

**Comment by An0n3m0us** [comment]
output

Most of the buttons are fixed now; all that remains is the vote button.

**Comment by An0n3m0us** [comment]
Flag reasons are now working again:

image

**Comment by MatthiasSaihttam** [comment]
Vote button shouldn’t be difficult, the underlying requests haven’t changed, as of a couple weeks ago, and I think the ScratchPadUI still exists.

**Comment by An0n3m0us** [comment]
> Vote button shouldn’t be difficult, the underlying requests haven’t changed, as of a couple weeks ago, and I think the ScratchPadUI still exists.

Yeah, I've almost got it working.

> We might want to undo our CSS changes as well, since KA is officially blue now.

Okay, will do

> Does the report button still work/is the form still checked by anyone? I wasn’t around when that was implemented, so I don’t know.

Doesn't work; it links to:
https://reportqueue.herokuapp.com/submit?type=program&id=$ID&callback=$URL
image

**Comment by An0n3m0us** [comment]
The Vote button code is not quite fixed yet, but I should have it done by tomorrow sometime.
As for the updating of the flag count, that should be quite simple to implement.
But the flag reasons might be a little harder to update as it would have to determine which flag type was selected.

What should be done about the Report button now that it's clear that its functionality is broken?
Should it still show up or not?

**Comment by MatthiasSaihttam** [comment]
I think just removing the report button would be best.

@An0n3m0us Any progress on this?

**Comment by An0n3m0us** [comment]
I'm aiming to continue work on this around mid May and hopefully finish off with the vote button functionality, which is causing me a little trouble.
But I guess it's fine if it remains closed for now.

**Comment by MatthiasSaihttam** [comment]
I think I fixed the buttons in my most recent commit to master, that's why I closed it.

**Pull request closed without merging**
